// seed.js — the proposed starting curriculum, A1 → C1.
//
// SOURCING: this is not lifted from any single app's internal unit list
// (no formal course publishes one at that granularity). It's built from the
// standard CEFR / Goethe-Institut topic-and-grammar progression that nearly
// every serious German course (Schritte international, Netzwerk, Aspekte,
// Goethe-Zertifikat exam syllabuses) follows — greetings before cases,
// Perfekt before Konjunktiv, etc. Vocab favors natural spoken phrasing
// ("Ich hätte gern...", "Hast du Lust auf...?") alongside the formal/
// textbook form where the two diverge, since the goal includes being able
// to actually hold a conversation in Germany or Austria, not just pass a
// written exam.
//
// This is a starting point, not a fixed syllabus -- everything here is fully
// editable in the Curriculum Editor afterward (rename, reorder, merge,
// delete, add). Treat the 40 units below as a strong skeleton to flesh out
// or rearrange, not a finished product.

export const SEED_CURRICULUM = {
  sections: [
    {
      key: 'first-contact',
      title: 'First Contact',
      position: 0,
      notes: 'A1.1 -- the absolute basics: greetings, numbers, talking about yourself.',
      units: [
        {
          title: 'Greetings & Introductions',
          source: 'CEFR',
          objectives: ['greet people formally and informally', 'introduce yourself', "ask someone's name"],
          grammar_focus: ['sein (present tense)', 'du vs. Sie'],
          vocab: [
            { german: 'Hallo', english: 'hello' },
            { german: 'Guten Tag', english: 'good day', notes: 'formal greeting, used with strangers' },
            { german: 'Ich heiße…', english: 'my name is…' },
            { german: 'Wie heißt du?', english: "what's your name? (informal)" },
            { german: 'Freut mich', english: 'nice to meet you' },
            { german: 'Guten Abend', english: 'Good evening' },
            { german: 'Auf Wiedersehen', english: 'Goodbye', notes: 'formal' },
            { german: 'Tschüss', english: 'Bye', notes: 'informal' },
            { german: 'Ich bin', english: 'I am', notes: 'used for introductions with sein' },
            { german: 'Wie geht es dir?', english: 'How are you?', notes: 'informal' },
            { german: 'Wie geht es Ihnen?', english: 'How are you?', notes: 'formal' },
            { german: 'Mir geht es gut', english: "I'm fine" },
            { german: 'Ich komme aus...', english: 'I am from...', notes: 'used to talk about your origin' },
            { german: 'der Name', english: 'the name' },
            { german: 'die Familie', english: 'the family' },
            { german: 'Ich bin Student', english: 'I am a student', notes: 'example sentence with sein' },
            { german: 'Woher kommst du?', english: 'Where are you from?', notes: 'informal' },
            { german: 'Woher kommen Sie?', english: 'Where are you from?', notes: 'formal' },
          ],
        },
        {
          title: 'Numbers, Time & Days',
          source: 'CEFR',
          objectives: ['count and use numbers', 'tell the time', 'name the days and months'],
          grammar_focus: ['cardinal numbers', 'time expressions (Wie spät ist es?)'],
          vocab: [
            { german: 'eins, zwei, drei', english: 'one, two, three' },
            { german: 'Wie spät ist es?', english: 'what time is it?' },
            { german: 'der Montag', english: 'Monday' },
            { german: 'heute / morgen / gestern', english: 'today / tomorrow / yesterday' },
            { german: 'um … Uhr', english: "at … o'clock" },
            { german: 'vier', english: 'four' },
            { german: 'fünf', english: 'five' },
            { german: 'sechs', english: 'six' },
            { german: 'sieben', english: 'seven' },
            { german: 'acht', english: 'eight' },
            { german: 'neun', english: 'nine' },
            { german: 'zehn', english: 'ten' },
            { german: 'die Stunde', english: 'the hour', notes: "used in time expressions like 'Eine Stunde' (one hour)" },
            { german: 'die Minute', english: 'the minute', notes: "used in time expressions like 'fünf Minuten' (five minutes)" },
            { german: 'der Dienstag', english: 'Tuesday' },
            { german: 'der Mittwoch', english: 'Wednesday' },
            { german: 'der Donnerstag', english: 'Thursday' },
            { german: 'der Freitag', english: 'Friday' },
            { german: 'das Wochenende', english: 'the weekend' },
            { german: 'Ich bin um ... Uhr da', english: "I'll be there at ... o'clock", notes: 'natural way to express arrival time' },
            { german: 'Kommst du morgen?', english: 'Are you coming tomorrow?', notes: "example of using 'morgen' in a question" },
          ],
        },
        {
          title: 'Talking About Yourself',
          source: 'CEFR',
          objectives: ['state your origin and nationality', 'talk about basic possessions', 'ask w-questions'],
          grammar_focus: ['haben (present tense)', 'possessive pronouns (mein/dein)', 'w-questions (wo, wer, was)'],
          vocab: [
            { german: 'Ich komme aus…', english: 'I come from…' },
            { german: 'Woher kommst du?', english: 'where are you from?', notes: 'woher = from where; distinct from wo (location) and wohin (to where).' },
            { german: 'mein / meine', english: 'my (masc./fem.)' },
            { german: 'ich habe', english: 'I have' },
            { german: 'der Beruf', english: 'profession, job' },
            { german: 'Österreich', english: 'Austria', notes: 'Spelling to reinforce: Ö-ster-reich.' },
            { german: 'dein', english: 'your' },
            { german: 'wo wohnst du?', english: 'where do you live?' },
            { german: 'ich bin', english: 'I am', notes: 'used for introductions' },
            { german: 'wer bist du?', english: 'who are you?' },
            { german: 'was hast du?', english: 'what do you have?' },
            { german: 'das ist mein...', english: "that's my...", notes: 'used to describe possessions' },
            { german: 'ich habe eine Familie', english: 'I have a family' },
            { german: 'wie alt bist du?', english: 'how old are you?' },
            { german: 'ich bin ... Jahre alt', english: 'I am ... years old' },
            { german: 'das ist mein Mann/Frau', english: "that's my husband/wife" },
          ],
        },
      ],
    },
    {
      key: 'everyday-basics',
      title: 'Everyday Basics',
      position: 1,
      notes: 'A1.2 -- family, food, shopping, getting around.',
      units: [
        {
          title: 'Family & People',
          source: 'CEFR',
          objectives: ['name family members', 'describe people simply', 'use possessives across genders'],
          grammar_focus: ['possessive adjectives (sein/ihr)', 'plural noun forms'],
          vocab: [
            { german: 'die Familie', english: 'the family' },
            { german: 'die Mutter / der Vater', english: 'mother / father' },
            { german: 'die Geschwister', english: 'siblings' },
            { german: 'verheiratet', english: 'married' },
            { german: 'das Kind, die Kinder', english: 'child, children' },
            { german: 'der Bruder', english: 'brother' },
            { german: 'die Schwester', english: 'sister' },
            { german: 'der Sohn', english: 'son' },
            { german: 'die Tochter', english: 'daughter' },
            { german: 'der Opa', english: 'grandfather' },
            { german: 'die Oma', english: 'grandmother' },
            { german: 'der Ehemann', english: 'husband' },
            { german: 'die Ehefrau', english: 'wife' },
            { german: 'sein Mann', english: 'her husband', notes: 'possessive adjective usage' },
            { german: 'ihre Frau', english: 'his wife', notes: 'possessive adjective usage' },
            { german: 'Wie alt bist du?', english: 'How old are you?', notes: 'common question in introductions' },
            { german: 'Ich bin verheiratet mit...', english: 'I am married to...', notes: 'introducing spouse' },
            { german: 'Ich habe einen Sohn / eine Tochter', english: 'I have a son / a daughter', notes: 'talking about children' },
            { german: 'Das ist mein Bruder / meine Schwester', english: 'This is my brother / sister', notes: 'introducing siblings' },
          ],
        },
        {
          title: 'Café & Restaurant',
          source: 'CEFR',
          objectives: ['order food and drink', 'ask for the bill', 'express preferences politely'],
          grammar_focus: ['möchten (would like)', 'accusative case -- intro'],
          vocab: [
            { german: 'ich möchte', english: 'I would like', notes: "Watch the umlaut: möchte, NOT mochte (that's past tense of mögen)." },
            { german: 'Ich hätte gern…', english: 'I would like to have…', notes: 'More natural in spoken German than "ich möchte" when ordering.' },
            { german: 'die Speisekarte', english: 'the menu' },
            { german: 'Die Rechnung, bitte', english: 'the bill, please' },
            { german: 'lecker', english: 'tasty, delicious', notes: 'Common everyday praise word for food.' },
            { german: 'ausgezeichnet', english: 'excellent', notes: 'Spelling to reinforce: aus-ge-zeich-net.' },
            { german: 'das Menü', english: 'the menu' },
            { german: 'ein Tisch für zwei, bitte', english: 'a table for two, please' },
            { german: 'das Bier', english: 'the beer' },
            { german: 'ein Kaffee, bitte', english: 'a coffee, please' },
            { german: 'ich bin allergisch gegen...', english: 'I am allergic to...', notes: 'useful for special dietary needs' },
            { german: 'können Sie mir empfehlen?', english: 'can you recommend something?' },
            { german: 'das Wasser, bitte', english: 'water, please' },
            { german: 'die Karte', english: 'the card (as in credit card)', notes: 'for paying the bill' },
            { german: 'bar bezahlen', english: 'to pay cash' },
            { german: 'ich nehme...', english: "I'll have...", notes: "alternative to 'ich möchte'" },
            { german: 'gibt es...?', english: 'is there...?', notes: 'to ask about availability of something' },
          ],
        },
        {
          title: 'Shopping & Money',
          source: 'CEFR',
          objectives: ['ask prices', 'shop for clothes and groceries', 'handle a basic transaction'],
          grammar_focus: ['accusative with direct objects', 'dieser/diese/dieses'],
          vocab: [
            { german: 'Was kostet das?', english: 'what does that cost?' },
            { german: 'Das ist mir zu teuer', english: "that's too expensive for me" },
            { german: 'die Kleidung', english: 'clothing' },
            { german: 'bar / mit Karte zahlen', english: 'to pay cash / by card' },
            { german: 'der Einkaufswagen', english: 'the shopping cart' },
            { german: 'Ich suche', english: 'I am looking for' },
            { german: 'Wo ist...?', english: 'Where is...?', notes: 'e.g. Wo ist die Milch?' },
            { german: 'Ich brauche', english: 'I need' },
            { german: 'das Obstkorb', english: 'the fruit basket' },
            { german: 'die Getränke', english: 'the beverages' },
            { german: 'Ich nehme', english: "I'll take", notes: 'e.g. Ich nehme diese Tomaten' },
            { german: 'Wie viel wiegt das?', english: 'How much does it weigh?', notes: 'for produce or bulk goods' },
            { german: 'Ich möchte', english: 'I would like', notes: 'polite way to express a desire' },
            { german: 'die Kasse', english: 'the checkout' },
            { german: 'das Wechselgeld', english: 'the change' },
          ],
        },
        {
          title: 'Directions & Getting Around',
          source: 'CEFR',
          objectives: ['ask for and follow directions', 'use public transport'],
          grammar_focus: ['wo vs. wohin vs. woher', 'dative after prepositions (aus, zu, mit)'],
          vocab: [
            { german: 'Wo ist…?', english: 'where is…?', notes: 'wo = location; wohin = motion toward; woher = origin.' },
            { german: 'links / rechts / geradeaus', english: 'left / right / straight ahead' },
            { german: 'die Haltestelle', english: 'the (bus/tram) stop' },
            { german: 'Wie komme ich zu…?', english: 'how do I get to…?' },
            { german: 'die Kreuzung', english: 'the intersection' },
            { german: 'die Straße', english: 'the street' },
            { german: 'die Bushaltestelle', english: 'the bus stop' },
            { german: 'der Bahnhof', english: 'the train station' },
            { german: 'ich verstehe nicht', english: "I don't understand", notes: 'useful when asking for directions' },
            { german: 'können Sie mir helfen?', english: 'can you help me?', notes: 'polite way to ask for assistance' },
            { german: 'ich bin verloren', english: 'I am lost', notes: 'useful phrase when needing directions' },
            { german: 'die U-Bahn', english: 'the subway' },
            { german: 'ein Ticket kaufen', english: 'to buy a ticket', notes: 'useful at public transport stations' },
            { german: 'die Fahrkarte', english: 'the ticket' },
            { german: 'ich möchte zur...', english: 'I would like to go to...', notes: 'useful when asking for directions to a specific place' },
            { german: 'wie viel kostet das?', english: 'how much does it cost?', notes: 'useful when buying tickets or asking about prices' },
          ],
        },
      ],
    },
    {
      key: 'home-routine',
      title: 'Home & Routine',
      position: 2,
      notes: 'A1.3 -> A2.1 -- describing your home and daily life.',
      units: [
        {
          title: 'Housing & Furniture',
          source: 'CEFR',
          objectives: ['describe a home', 'name rooms and furniture', 'use es gibt'],
          grammar_focus: ['es gibt + accusative', 'prepositions of place (in, auf, unter) + dative'],
          vocab: [
            { german: 'die Wohnung', english: 'the apartment' },
            { german: 'das Zimmer', english: 'the room' },
            { german: 'es gibt', english: 'there is / there are' },
            { german: 'der Schreibtisch', english: 'the desk' },
            { german: 'gemütlich', english: 'cozy' },
            { german: 'das Bett', english: 'the bed' },
            { german: 'der Tisch', english: 'the table' },
            { german: 'der Stuhl', english: 'the chair' },
            { german: 'das Sofa', english: 'the sofa' },
            { german: 'die Küche', english: 'the kitchen' },
            { german: 'das Badezimmer', english: 'the bathroom' },
            { german: 'der Teppich', english: 'the carpet' },
            { german: 'die Lampe', english: 'the lamp' },
            { german: 'in der Wohnung wohnen', english: 'to live in the apartment' },
            { german: 'auf dem Tisch', english: 'on the table', notes: 'preposition of place + dative' },
            { german: 'unter dem Bett', english: 'under the bed', notes: 'preposition of place + dative' },
            { german: 'ich möbeliere mein Zimmer', english: "I'm furnishing my room" },
          ],
        },
        {
          title: 'Daily Routine',
          source: 'CEFR',
          objectives: ['describe a typical day', 'use reflexive and separable verbs'],
          grammar_focus: ['reflexive verbs (sich duschen)', 'separable-prefix verbs (aufstehen)'],
          vocab: [
            { german: 'aufstehen', english: 'to get up', notes: 'Separable: "Ich stehe um 7 Uhr auf."' },
            { german: 'sich duschen', english: 'to shower' },
            { german: 'frühstücken', english: 'to eat breakfast' },
            { german: 'der Alltag', english: 'everyday life, routine' },
            { german: 'meistens', english: 'usually, mostly' },
            { german: 'der Wecker', english: 'alarm clock' },
            { german: 'sich anziehen', english: 'to get dressed' },
            { german: 'zum Frühstück', english: 'for breakfast', notes: "used in phrases like 'Ich esse zum Frühstück...'" },
            { german: 'der Morgen', english: 'morning' },
            { german: 'abends', english: 'in the evening', notes: 'common adverbial phrase' },
            { german: 'zur Arbeit gehen', english: 'to go to work', notes: 'common separable verb construction' },
            { german: 'sich ausruhen', english: 'to rest', notes: 'reflexive verb for taking a break' },
            { german: 'das Bett machen', english: 'to make the bed', notes: 'common daily chore' },
            { german: 'sich fertig machen', english: 'to get ready', notes: 'reflexive verb for preparing oneself' },
            { german: 'der Tagesablauf', english: 'daily routine', notes: "synonym for 'der Alltag'" },
            { german: 'ich gehe ins Bett', english: 'I go to bed', notes: 'natural way to express going to sleep' },
          ],
        },
        {
          title: 'Weather & Seasons',
          source: 'CEFR',
          objectives: ['discuss the weather and seasons', 'use impersonal "es"'],
          grammar_focus: ['impersonal verbs (es regnet)', 'adjective agreement'],
          vocab: [
            { german: 'Wie ist das Wetter?', english: "how's the weather?" },
            { german: 'es regnet / es schneit', english: "it's raining / it's snowing" },
            { german: 'der Sommer / der Winter', english: 'summer / winter' },
            { german: 'warm / kalt', english: 'warm / cold' },
            { german: 'die Jahreszeit', english: 'the season' },
            { german: 'es ist sonnig', english: "it's sunny" },
            { german: 'der Frühling', english: 'spring' },
            { german: 'der Herbst', english: 'autumn' },
            { german: 'es ist bewölkt', english: "it's cloudy" },
            { german: 'die Temperatur', english: 'temperature' },
            { german: 'es ist windig', english: "it's windy" },
            { german: 'ich friere', english: "I'm cold", notes: 'expressing personal feeling' },
            { german: 'mir ist heiß', english: "I'm hot", notes: 'expressing personal feeling' },
            { german: 'es gibt Regen', english: "there's rain", notes: "alternative to 'es regnet'" },
            { german: 'der Wetterbericht', english: 'weather forecast' },
          ],
        },
      ],
    },
    {
      key: 'the-past',
      title: 'The Past',
      position: 3,
      notes: 'A2.1 -- narrating completed actions.',
      units: [
        {
          title: 'Perfekt — Regular Verbs',
          source: 'CEFR',
          objectives: ['form the present perfect with weak verbs', 'narrate simple completed actions'],
          grammar_focus: ['haben + ge-(stem)-t', 'position of the past participle'],
          vocab: [
            { german: 'gemacht', english: 'made, done', notes: 'from machen' },
            { german: 'gespielt', english: 'played', notes: 'from spielen' },
            { german: 'gearbeitet', english: 'worked', notes: 'from arbeiten' },
            { german: 'gekauft', english: 'bought', notes: 'from kaufen' },
            { german: 'Ich habe … gemacht', english: 'I did/made …' },
            { german: 'gegessen', english: 'eaten' },
            { german: 'getrunken', english: 'drunk' },
            { german: 'Ich habe gestern Abend gegessen', english: 'I ate yesterday evening', notes: 'example sentence for present perfect' },
            { german: 'die Wohnung', english: 'the apartment', notes: 'common noun to use with haben' },
            { german: 'gereist', english: 'travelled' },
            { german: 'Ich habe letztes Jahr gereist', english: 'I travelled last year', notes: 'example sentence for present perfect' },
            { german: 'das Essen', english: 'the meal', notes: 'common noun to use with haben' },
            { german: 'gelesen', english: 'read' },
            { german: 'Ich habe das Buch gelesen', english: 'I have read the book', notes: 'example sentence for present perfect' },
            { german: 'geschlafen', english: 'slept' },
          ],
        },
        {
          title: 'Perfekt — Irregular & Sein-Verbs',
          source: 'CEFR',
          objectives: ['form Perfekt with strong verbs', 'use sein-verbs for motion/change of state'],
          grammar_focus: ['sein + ge-(stem)-en', 'common irregular participles'],
          vocab: [
            { german: 'gegangen', english: 'gone, walked', notes: 'sein + gegangen' },
            { german: 'gefahren', english: 'driven, traveled', notes: 'sein + gefahren' },
            { german: 'gegessen', english: 'eaten', notes: 'haben + gegessen' },
            { german: 'gesehen', english: 'seen', notes: 'haben + gesehen' },
            { german: 'geblieben', english: 'stayed', notes: 'sein + geblieben' },
            { german: 'gekommen', english: 'come' },
            { german: 'gewesen', english: 'been' },
            { german: 'gekümmert', english: 'taken care of', notes: "used in phrases like 'Ich habe mich gekümmert um...'" },
            { german: 'gebracht', english: 'brought' },
            { german: 'genommen', english: 'taken' },
            { german: 'geheißen', english: 'been called', notes: 'used for introducing oneself or talking about names' },
            { german: 'gewohnt', english: 'lived' },
            { german: 'das Ziel', english: 'the goal', notes: "used in phrases like 'Ich bin mein Ziel erreicht' (I reached my goal)" },
            { german: 'die Erfahrung', english: 'the experience', notes: "used in phrases like 'Ich habe eine gute Erfahrung gemacht' (I had a good experience)" },
            { german: 'Ich bin nach Hause gegangen', english: 'I went home', notes: 'example sentence using sein-verb' },
            { german: 'Ich bin zum Arzt gegangen', english: 'I went to the doctor', notes: 'example sentence using sein-verb' },
          ],
        },
        {
          title: 'Last Weekend',
          source: 'CEFR',
          objectives: ['narrate a recent event in sequence', 'use time connectors'],
          grammar_focus: ['time connectors (zuerst, dann, danach, zum Schluss)'],
          vocab: [
            { german: 'letztes Wochenende', english: 'last weekend' },
            { german: 'zuerst / dann / danach', english: 'first / then / afterward' },
            { german: 'es war…', english: 'it was…' },
            { german: "Wie war's?", english: 'how was it?', notes: 'Very natural conversational question.' },
            { german: 'total', english: 'totally, really', notes: 'Colloquial intensifier: "Es war total schön."' },
            { german: 'am Samstag', english: 'on Saturday' },
            { german: 'am Sonntag', english: 'on Sunday' },
            { german: 'ich bin zum Bahnhof gegangen', english: 'I went to the train station', notes: 'common action on weekends' },
            { german: 'ich habe meine Freunde getroffen', english: 'I met my friends' },
            { german: 'wir sind ins Kino gegangen', english: 'we went to the cinema', notes: 'typical weekend activity' },
            { german: 'zum Schluss', english: 'finally', notes: 'time connector to conclude a sequence of events' },
            { german: 'ich war müde', english: 'I was tired', notes: 'common feeling after a busy weekend' },
            { german: 'das war lustig', english: 'that was funny', notes: 'to share a humorous experience' },
            { german: 'ich habe ein gutes Essen gegessen', english: 'I had a good meal', notes: 'to talk about food' },
            { german: 'ich bin nach Hause gegangen', english: 'I went home', notes: 'common conclusion to a day out' },
          ],
        },
      ],
    },
    {
      key: 'plans-travel',
      title: 'Plans & Travel',
      position: 4,
      notes: 'A2.2 -- the future, travel, invitations.',
      units: [
        {
          title: 'Future Plans',
          source: 'CEFR',
          objectives: ['talk about future plans', 'use werden and present-as-future'],
          grammar_focus: ['werden + infinitive', 'present tense as future with time markers'],
          vocab: [
            { german: 'ich werde…', english: 'I will…' },
            { german: 'vorhaben', english: 'to plan, intend', notes: '"Was hast du vor?" = What are your plans?' },
            { german: 'nächste Woche', english: 'next week' },
            { german: 'bald', english: 'soon' },
            { german: 'vielleicht', english: 'maybe, perhaps' },
            { german: 'morgen', english: 'tomorrow' },
            { german: 'übermorgen', english: 'the day after tomorrow' },
            { german: 'in einem Monat', english: 'in a month' },
            { german: 'das Wochenende', english: 'the weekend' },
            { german: 'die Ferien', english: 'the holidays' },
            { german: 'reisen', english: 'to travel' },
            { german: 'eine Reise buchen', english: 'to book a trip' },
            { german: 'ein Ticket kaufen', english: 'to buy a ticket' },
            { german: 'ich freue mich darauf', english: "I'm looking forward to it" },
            { german: 'ich denke daran', english: "I'm thinking about it" },
            { german: 'das ist geplant', english: "that's planned" },
          ],
        },
        {
          title: 'Travel & Vacation',
          source: 'CEFR',
          objectives: ['discuss travel plans and experiences', 'handle basic travel booking language'],
          grammar_focus: ['prepositions of place with countries (in, nach)', 'accusative/dative review'],
          vocab: [
            { german: 'der Urlaub', english: 'the vacation' },
            { german: 'die Reise', english: 'the trip' },
            { german: 'Ich fliege nach…', english: "I'm flying to…", notes: '"nach" for cities/countries without an article.' },
            { german: 'die Unterkunft', english: 'the accommodation' },
            { german: 'Gute Reise!', english: 'have a good trip!', notes: 'Natural farewell phrase.' },
            { german: 'das Ziel', english: 'the destination' },
            { german: 'in Deutschland', english: 'in Germany', notes: 'preposition of place with country' },
            { german: 'nach Österreich fahren', english: 'to travel to Austria', notes: "using 'nach' with country" },
            { german: 'die Stadt', english: 'the city' },
            { german: 'am Flughafen', english: 'at the airport', notes: 'preposition of place' },
            { german: 'die Fahrkarte', english: 'the ticket' },
            { german: 'ich buche ein Ticket', english: 'I book a ticket', notes: 'basic travel booking language' },
            { german: 'die Abfahrt', english: 'the departure' },
            { german: 'die Ankunft', english: 'the arrival' },
            { german: 'Wie viel kostet die Reise?', english: 'How much does the trip cost?', notes: 'practical question for travel planning' },
            { german: 'Ich brauche einen Flug von Berlin nach München', english: 'I need a flight from Berlin to Munich', notes: 'example of travel booking language' },
          ],
        },
        {
          title: 'Invitations & Appointments',
          source: 'CEFR',
          objectives: ['make, accept, and decline invitations', 'arrange a meeting time'],
          grammar_focus: ['modal verbs review (können/möchten)', 'question word order'],
          vocab: [
            { german: 'Hast du Lust auf…?', english: 'do you feel like…?', notes: 'Natural, casual way to invite someone -- more relaxed than "möchtest du".' },
            { german: 'Ich habe leider keine Zeit', english: "unfortunately I don't have time" },
            { german: 'der Termin', english: 'the appointment' },
            { german: 'Passt dir…?', english: 'does … work for you?', notes: 'Natural scheduling phrase.' },
            { german: 'Klar, gerne!', english: 'sure, gladly!', notes: 'Natural enthusiastic acceptance.' },
            { german: 'ein Treffen', english: 'a meeting' },
            { german: 'ich würde gerne', english: 'I would like to', notes: 'used to accept invitations' },
            { german: 'können wir uns treffen', english: 'can we meet' },
            { german: 'das passt mir nicht', english: "that doesn't suit me", notes: 'used to decline invitations' },
            { german: 'ein Wochenende', english: 'a weekend' },
            { german: 'möchtest du mitkommen', english: 'do you want to come along', notes: 'used to extend an invitation' },
            { german: 'ich bin verhindert', english: 'I am prevented', notes: 'used to decline invitations due to prior commitments' },
            { german: 'wie wäre es mit', english: 'how about', notes: 'used to suggest alternatives' },
            { german: 'das kriegen wir hin', english: "we'll manage that", notes: 'used to confirm arrangements' },
            { german: 'ich freue mich darauf', english: "I'm looking forward to it" },
          ],
        },
      ],
    },
    {
      key: 'body-health-freetime',
      title: 'Body, Health & Free Time',
      position: 5,
      notes: 'A2.3 -- health, hobbies, sport.',
      units: [
        {
          title: "At the Doctor's",
          source: 'CEFR',
          objectives: ['describe symptoms', 'understand basic medical advice'],
          grammar_focus: ['müssen/sollen for advice and obligation', 'dative construction: [body part] tut mir weh'],
          vocab: [
            { german: 'Mir tut der Kopf weh', english: 'my head hurts', notes: 'Dative construction: [body part] tut mir weh.' },
            { german: 'der Schmerz', english: 'the pain' },
            { german: 'die Apotheke', english: 'the pharmacy' },
            { german: 'Ich fühle mich krank', english: 'I feel sick' },
            { german: 'Gute Besserung', english: 'get well soon', notes: 'Said to someone who is sick.' },
            { german: 'die Symptome', english: 'the symptoms' },
            { german: 'Ich habe Fieber', english: 'I have a fever' },
            { german: 'der Arzt', english: 'the doctor' },
            { german: 'die Diagnose', english: 'the diagnosis' },
            { german: 'die Medikamente', english: 'the medication' },
            { german: 'Ich muss zum Arzt gehen', english: 'I have to go to the doctor', notes: 'using müssen for obligation' },
            { german: 'Sie sollten sich ausruhen', english: 'You should rest', notes: 'using sollen for advice' },
            { german: 'Mir tut der Rücken weh', english: 'My back hurts', notes: 'dative construction for body parts' },
            { german: 'Ich brauche einen Termin', english: 'I need an appointment' },
            { german: 'Kann ich bitte einen Arzt aufsuchen?', english: 'Can I see a doctor, please?', notes: 'polite request' },
            { german: 'Ich habe Schmerzen im Bauch', english: 'I have stomach ache', notes: 'common symptom description' },
          ],
        },
        {
          title: 'Hobbies & Interests',
          source: 'CEFR',
          objectives: ['describe hobbies', 'express degrees of preference'],
          grammar_focus: ['gern / lieber / am liebsten', 'verb + gern'],
          vocab: [
            { german: 'Ich spiele gern…', english: 'I like to play…' },
            { german: 'am liebsten', english: 'most of all, favorite', notes: 'Superlative form of gern.' },
            { german: 'die Freizeit', english: 'free time' },
            { german: 'langweilig / spannend', english: 'boring / exciting' },
            { german: 'Was machst du gern?', english: 'what do you like to do?', notes: 'Natural conversational opener.' },
            { german: 'der Sport', english: 'sports' },
            { german: 'die Bewegung', english: 'exercise/movement' },
            { german: 'ich gehe gern spazieren', english: 'I like to go for a walk', notes: 'common leisure activity' },
            { german: 'das Fitnessstudio', english: 'gym', notes: 'relevant for health and fitness' },
            { german: 'ich schwimme gern', english: 'I like to swim', notes: 'popular recreational activity' },
            { german: 'der Garten', english: 'garden', notes: 'for those who enjoy gardening' },
            { german: 'ich lese gern Bücher', english: 'I like to read books', notes: 'common hobby' },
            { german: 'das Radfahren', english: 'cycling', notes: 'popular in Germany and Austria' },
            { german: 'ich tanze gern', english: 'I like to dance', notes: 'for various dance styles' },
            { german: 'die Musik', english: 'music', notes: 'important for expressing interests' },
            { german: 'ich höre gern Musik', english: 'I like to listen to music', notes: 'common way to enjoy music' },
          ],
        },
        {
          title: 'Sports & Leisure',
          source: 'CEFR',
          objectives: ['discuss sports activities', 'make plans for leisure time'],
          grammar_focus: ['verb + accusative object review', 'prepositional verbs (sich interessieren für)'],
          vocab: [
            { german: 'Sport treiben', english: 'to do/play sports' },
            { german: 'sich interessieren für', english: 'to be interested in' },
            { german: 'joggen / schwimmen / wandern', english: 'to jog / swim / hike' },
            { german: 'der Verein', english: 'the club (e.g. sports club)' },
            { german: 'Lust haben', english: 'to feel like (doing something)', notes: 'Reused naturally: "Hast du Lust mitzukommen?"' },
            { german: 'der Fitnessstudio', english: 'fitness studio' },
            { german: 'Rad fahren', english: 'to ride a bike' },
            { german: 'der Ball', english: 'ball', notes: 'commonly used for various sports' },
            { german: 'sich erholen', english: 'to recover', notes: 'used after exercise or a long day' },
            { german: 'die Freizeit', english: 'leisure time' },
            { german: 'der Park', english: 'park', notes: 'common place for leisure activities' },
            { german: 'spazieren gehen', english: 'to go for a walk' },
            { german: 'sich bewegen', english: 'to move/exercise', notes: 'general term for physical activity' },
            { german: 'der Sportplatz', english: 'sports field' },
            { german: 'ein Turnier', english: 'tournament', notes: 'used for competitive sports events' },
          ],
        },
      ],
    },
    {
      key: 'work-practical-life',
      title: 'Work & Practical Life',
      position: 6,
      notes: 'A2.4 -> A2.5 -- jobs, errands, comparisons.',
      units: [
        {
          title: 'Jobs & Workplace',
          source: 'CEFR',
          objectives: ['describe your job and workplace', 'talk about job duties'],
          grammar_focus: ['von Beruf', 'present tense for habitual work activities'],
          vocab: [
            { german: 'von Beruf', english: 'by profession', notes: '"Ich bin Lehrer von Beruf."' },
            { german: 'das Büro', english: 'the office' },
            { german: 'der Kollege / die Kollegin', english: 'colleague (m./f.)' },
            { german: 'Ich arbeite als…', english: 'I work as…' },
            { german: 'die Besprechung', english: 'the meeting' },
            { german: 'der Job', english: 'the job' },
            { german: 'die Firma', english: 'the company' },
            { german: 'der Chef', english: 'the boss' },
            { german: 'die Schicht', english: 'the shift' },
            { german: 'arbeiten von 9 bis 5', english: 'to work from 9 to 5', notes: 'common way to describe a standard workday' },
            { german: 'die Aufgaben', english: 'the tasks' },
            { german: 'ich bin verantwortlich für', english: 'I am responsible for' },
            { german: 'ich mache das', english: 'I do that', notes: 'used to describe job duties' },
            { german: 'die Pause', english: 'the break' },
            { german: 'ich bin im Homeoffice', english: 'I am working from home', notes: 'common in modern work life' },
            { german: 'die Teamsitzung', english: 'the team meeting' },
            { german: 'ich bin im Urlaub', english: 'I am on vacation' },
          ],
        },
        {
          title: 'Bank, Post & Bureaucracy',
          source: 'CEFR',
          objectives: ['handle errands at a bank or post office', 'navigate basic German bureaucracy'],
          grammar_focus: ['polite requests (Ich hätte gern / Könnten Sie…)', 'modal verbs in formal register'],
          vocab: [
            { german: 'ein Konto eröffnen', english: 'to open an account' },
            { german: 'das Formular ausfüllen', english: 'to fill out the form' },
            { german: 'die Anmeldung', english: 'the registration', notes: "e.g. at the Einwohnermeldeamt (residents' registration office)." },
            { german: 'Könnten Sie mir helfen?', english: 'could you help me?', notes: 'Polite formal request.' },
            { german: 'der Briefumschlag', english: 'the envelope' },
            { german: 'die Bankfiliale', english: 'the bank branch' },
            { german: 'der Schalter', english: 'the counter' },
            { german: 'die Kontonummer', english: 'the account number' },
            { german: 'die IBAN', english: 'the IBAN', notes: 'International Bank Account Number' },
            { german: 'der Überweisungsauftrag', english: 'the transfer order' },
            { german: 'Ich hätte gern eine Überweisung gemacht', english: 'I would like to make a transfer', notes: 'polite request' },
            { german: 'Könnten Sie mir den Saldo sagen?', english: 'Could you tell me the balance?', notes: 'asking for account balance' },
            { german: 'Ich möchte Geld abheben', english: 'I would like to withdraw money' },
            { german: 'die Gebühr', english: 'the fee' },
            { german: 'die Postleitzahl', english: 'the postal code' },
            { german: 'das Porto', english: 'the postage' },
            { german: 'Ich benötige ein Einschreiben', english: 'I need a registered letter' },
          ],
        },
        {
          title: 'Comparing Things',
          source: 'CEFR',
          objectives: ['compare people, places, and things'],
          grammar_focus: ['comparative and superlative adjectives (-er, am -sten)'],
          vocab: [
            { german: 'größer als', english: 'bigger than' },
            { german: 'am besten', english: 'the best', notes: 'Irregular superlative of gut.' },
            { german: 'genauso … wie', english: 'just as … as' },
            { german: 'im Vergleich zu', english: 'in comparison to' },
            { german: 'viel besser', english: 'much better' },
            { german: 'schneller', english: 'faster' },
            { german: 'billiger', english: 'cheaper' },
            { german: 'teurer', english: 'more expensive' },
            { german: 'leichter', english: 'easier' },
            { german: 'schwerer', english: 'heavier' },
            { german: 'der Preis', english: 'the price' },
            { german: 'die Qualität', english: 'the quality' },
            { german: 'das Angebot', english: 'the offer' },
            { german: 'ich bevorzuge', english: 'I prefer' },
            { german: 'ich finde, dass', english: 'I think that' },
            { german: 'das ist mir wichtiger', english: "that's more important to me" },
            { german: 'als nächstes', english: 'next', notes: 'used to compare and prioritize tasks or options' },
            { german: 'im Vergleich dazu', english: 'in comparison to that', notes: 'used to compare two things' },
            { german: 'ich denke, der eine ist besser', english: 'I think the one is better', notes: 'used in casual conversations to express opinions' },
          ],
        },
      ],
    },
    {
      key: 'opinions-reasons',
      title: 'Opinions & Reasons',
      position: 7,
      notes: 'B1.1 -- arguing a point, giving reasons, basic conditions.',
      units: [
        {
          title: 'Expressing Opinions',
          source: 'CEFR',
          objectives: ['state and justify opinions', 'agree and disagree'],
          grammar_focus: ['dass-clauses', 'ich finde/glaube/denke + dass'],
          vocab: [
            { german: 'Ich finde, dass…', english: 'I think that…', notes: 'dass sends the verb to the end of the clause.' },
            { german: 'meiner Meinung nach', english: 'in my opinion' },
            { german: 'Das stimmt', english: "that's right, true" },
            { german: 'Da bin ich anderer Meinung', english: 'I disagree', notes: 'More formal/explicit than just saying "nein".' },
            { german: 'na ja', english: 'well…', notes: 'Colloquial filler used when hedging an opinion.' },
            { german: 'eine Meinung haben', english: 'to have an opinion' },
            { german: 'ich bin der Meinung', english: 'I am of the opinion', notes: 'more formal than ich finde' },
            { german: 'ich denke, dass', english: 'I think that', notes: 'similar to ich glaube, dass' },
            { german: 'ich glaube nicht, dass', english: "I don't think that", notes: 'used to express disagreement' },
            { german: 'das ist mein Ernst', english: "I'm serious", notes: "used to emphasize one's opinion" },
            { german: 'ich stimme zu', english: 'I agree' },
            { german: 'ich stimme nicht zu', english: 'I disagree' },
            { german: 'das ist ein guter Punkt', english: "that's a good point", notes: "used to acknowledge someone's argument" },
            { german: 'das sehe ich anders', english: 'I see that differently', notes: 'polite way to express disagreement' },
            { german: 'ich verstehe, warum', english: 'I understand why', notes: "used to show understanding for someone's opinion" },
          ],
        },
        {
          title: 'Giving Reasons',
          source: 'CEFR',
          objectives: ['explain causes and reasons', 'link clauses with weil'],
          grammar_focus: ['weil-clauses (verb-final)', 'deshalb/deswegen (verb-second)'],
          vocab: [
            { german: 'weil', english: 'because', notes: 'Sends the verb to the end: "…, weil ich müde bin."' },
            { german: 'deshalb / deswegen', english: "therefore, that's why", notes: 'Triggers normal verb-second order, unlike weil.' },
            { german: 'der Grund', english: 'the reason' },
            { german: 'aus diesem Grund', english: 'for this reason' },
            { german: 'nämlich', english: 'namely, you see', notes: 'Common spoken connector that explains a reason.' },
            { german: 'die Ursache', english: 'the cause' },
            { german: 'deshalb bin ich hier', english: "that's why I'm here", notes: 'common conversational phrase' },
            { german: 'es liegt daran', english: "it's due to that", notes: 'used to explain reasons' },
            { german: 'das ist der Punkt', english: "that's the point", notes: 'to emphasize a reason' },
            { german: 'ich denke, dass', english: 'I think that', notes: 'to introduce an opinion or reason' },
            { german: 'es kommt daher', english: 'it comes from that', notes: 'to explain origins or causes' },
            { german: 'die Folge', english: 'the consequence' },
            { german: 'es hat nichts damit zu tun', english: 'it has nothing to do with that', notes: 'to dismiss a reason or connection' },
            { german: 'dafür gibt es einen guten Grund', english: "there's a good reason for that", notes: 'to justify something' },
            { german: 'aufgrund von', english: 'due to', notes: 'formal or written, but useful for B1 level' },
          ],
        },
        {
          title: 'Conditions',
          source: 'CEFR',
          objectives: ['express conditions and basic hypothetical situations'],
          grammar_focus: ['wenn-clauses (real conditions)', 'word order with wenn'],
          vocab: [
            { german: 'wenn', english: 'if, when', notes: 'Verb-final clause; differs from "wann" (interrogative "when").' },
            { german: 'falls', english: 'in case' },
            { german: 'Wenn ich Zeit habe, …', english: 'if I have time, …' },
            { german: 'unter der Bedingung, dass', english: 'on the condition that' },
            { german: 'sonst', english: 'otherwise' },
            { german: 'vorausgesetzt', english: 'provided that' },
            { german: 'die Voraussetzung', english: 'the condition' },
            { german: 'auf keinen Fall', english: 'under no circumstances', notes: 'used for strong conditions' },
            { german: 'solange', english: 'as long as' },
            { german: 'sofern', english: 'provided that', notes: 'more formal than vorausgesetzt' },
            { german: 'die Bedingung', english: 'the condition' },
            { german: 'abhängig davon', english: 'depending on', notes: 'used to express a condition that affects something' },
            { german: 'es sei denn', english: 'unless', notes: 'used to express an exception to a condition' },
            { german: 'im Falle, dass', english: 'in case', notes: 'used to express a possible future condition' },
          ],
        },
      ],
    },
    {
      key: 'narration',
      title: 'Narration',
      position: 8,
      notes: 'B1.2 -- telling stories, relative clauses, life history.',
      units: [
        {
          title: 'Präteritum for Storytelling',
          source: 'CEFR',
          objectives: ['use the simple past for narration, especially common verbs'],
          grammar_focus: ['Präteritum of sein/haben/modal verbs', 'written vs. spoken past usage'],
          vocab: [
            { german: 'ich war / ich hatte', english: 'I was / I had' },
            { german: 'es gab', english: 'there was/were' },
            { german: 'konnte / musste / wollte', english: 'could / had to / wanted to', notes: 'Präteritum of modal verbs.' },
            { german: 'damals', english: 'back then, at that time' },
            { german: 'Es war einmal…', english: 'once upon a time…', notes: "Classic fairy-tale opener -- a nice hook before reading German children's books." },
            { german: 'ich ging', english: 'I went' },
            { german: 'ich sah', english: 'I saw' },
            { german: 'ich sprach', english: 'I spoke', notes: 'less common in spoken language, but useful for writing' },
            { german: 'ich fuhr', english: 'I drove' },
            { german: 'ich las', english: 'I read' },
            { german: 'die Schule', english: 'school', notes: 'useful for talking about past experiences' },
            { german: 'der Sommer', english: 'summer', notes: 'common time frame for storytelling' },
            { german: 'ich verbrachte meine Kindheit in...', english: 'I spent my childhood in...', notes: 'natural way to start a story about the past' },
            { german: 'als ich klein war', english: 'when I was little' },
            { german: 'ich erinnere mich', english: 'I remember', notes: 'useful phrase for introducing a past event' },
            { german: 'das war toll', english: 'that was great', notes: 'common way to express a positive feeling about a past experience' },
            { german: 'ich machte', english: 'I did/made', notes: 'useful for talking about past actions or accomplishments' },
          ],
        },
        {
          title: 'Relative Clauses',
          source: 'CEFR',
          objectives: ['combine sentences using relative pronouns', 'add descriptive detail'],
          grammar_focus: ['relative pronouns (der/die/das)', 'case agreement in relative clauses'],
          vocab: [
            { german: 'der Mann, der…', english: 'the man who…' },
            { german: 'die Frau, die…', english: 'the woman who…' },
            { german: 'das Buch, das…', english: 'the book that…' },
            { german: 'mit dem/der…', english: 'with whom/which', notes: 'Dative relative pronoun.' },
            { german: 'dessen / deren', english: 'whose', notes: 'Genitive relative pronoun.' },
            { german: 'der Student, der neben mir wohnt', english: 'the student who lives next to me' },
            { german: 'die Stadt, in der ich aufgewachsen bin', english: 'the city where I grew up' },
            { german: 'das Restaurant, das ich letzte Woche ausprobiert habe', english: 'the restaurant I tried last week' },
            { german: 'die Straße, in der ich arbeite', english: 'the street where I work' },
            { german: 'der Bus, der mich zur Arbeit bringt', english: 'the bus that takes me to work' },
            { german: 'die Freundin, die mich gestern angerufen hat', english: 'the friend who called me yesterday' },
            { german: 'das Hotel, in dem ich übernachtet habe', english: 'the hotel where I stayed' },
            { german: 'der Lehrer, der mir Deutsch unterrichtet', english: 'the teacher who teaches me German' },
            { german: 'die Familie, die mich eingeladen hat', english: 'the family who invited me' },
          ],
        },
        {
          title: 'Personal History & Milestones',
          source: 'CEFR',
          objectives: ['talk about life events and personal history fluently'],
          grammar_focus: ['mixed past tense usage (Perfekt + Präteritum)', 'time expressions for life stages'],
          vocab: [
            { german: 'aufwachsen', english: 'to grow up' },
            { german: 'die Kindheit', english: 'the childhood' },
            { german: 'umziehen', english: 'to move (residence)' },
            { german: 'seitdem', english: 'since then' },
            { german: 'Ich bin aufgewachsen in…', english: 'I grew up in…' },
            { german: 'die Schulzeit', english: 'school days' },
            { german: 'das Studium', english: 'studies' },
            { german: 'die Ausbildung', english: 'apprenticeship/training' },
            { german: 'ich habe angefangen', english: 'I started', notes: 'often used with Perfekt' },
            { german: 'ich war damals', english: 'I was back then', notes: 'introduces a past situation' },
            { german: 'in meiner Jugend', english: 'in my youth' },
            { german: 'ich bin dann', english: 'then I', notes: 'used for sequencing events' },
            { german: 'als ich älter wurde', english: 'as I got older' },
            { german: 'vor ein paar Jahren', english: 'a few years ago' },
            { german: 'seit ich in Deutschland lebe', english: "since I've been living in Germany", notes: 'emphasizes a change or continuity' },
          ],
        },
      ],
    },
    {
      key: 'society-media',
      title: 'Society & Media',
      position: 9,
      notes: 'B1.3 -> B1.4 -- news, environment, formal register.',
      units: [
        {
          title: 'News & Current Events',
          source: 'CEFR',
          objectives: ['discuss news topics', 'understand headlines'],
          grammar_focus: ['passive voice -- recognition (wird gemacht)', 'nominal style in headlines'],
          vocab: [
            { german: 'die Nachrichten', english: 'the news' },
            { german: 'die Schlagzeile', english: 'the headline' },
            { german: 'berichten über', english: 'to report on' },
            { german: 'die Wirtschaft', english: 'the economy' },
            { german: 'laut einer Studie', english: 'according to a study', notes: 'Formal/journalistic phrase.' },
            { german: 'der Skandal', english: 'the scandal' },
            { german: 'die Öffentlichkeit', english: 'the public' },
            { german: 'diskutieren', english: 'to discuss' },
            { german: 'die Meinung', english: 'the opinion' },
            { german: 'ein Interview geben', english: 'to give an interview' },
            { german: 'die Kritik', english: 'the criticism' },
            { german: 'wird thematisiert', english: 'is being discussed', notes: 'example of passive voice' },
            { german: 'die soziale Medien', english: 'social media' },
            { german: 'ein Kommentar schreiben', english: 'to write a comment' },
            { german: 'die Berichterstattung', english: 'the reporting' },
            { german: 'sich informieren', english: 'to inform oneself' },
          ],
        },
        {
          title: 'Environment & Sustainability',
          source: 'CEFR',
          objectives: ['discuss environmental topics and personal habits'],
          grammar_focus: ['nominalized verbs (das Recyceln)', 'necessity (man muss/sollte)'],
          vocab: [
            { german: 'der Klimawandel', english: 'climate change' },
            { german: 'nachhaltig', english: 'sustainable' },
            { german: 'die Umwelt schützen', english: 'to protect the environment' },
            { german: 'den Müll trennen', english: 'to separate trash, recycle', notes: 'A very real everyday German cultural practice.' },
            { german: 'erneuerbare Energien', english: 'renewable energy' },
            { german: 'das Recyceln', english: 'recycling' },
            { german: 'die Abfallentsorgung', english: 'waste management' },
            { german: 'man muss weniger Plastik verwenden', english: 'one must use less plastic', notes: 'example sentence with necessity' },
            { german: 'der CO2-Fußabdruck', english: 'carbon footprint' },
            { german: 'die Luftverschmutzung', english: 'air pollution' },
            { german: 'man sollte öffentliche Verkehrsmittel nutzen', english: 'one should use public transportation', notes: 'example sentence with advice' },
            { german: 'das Kompostieren', english: 'composting' },
            { german: 'die Energieeffizienz', english: 'energy efficiency' },
            { german: 'man muss Wasser sparen', english: 'one must save water', notes: 'example sentence with necessity' },
            { german: 'die Umweltverschmutzung', english: 'environmental pollution' },
          ],
        },
        {
          title: 'Genitive & Formal Register',
          source: 'CEFR',
          objectives: ['use the genitive case', 'recognize formal/written register'],
          grammar_focus: ['genitive case (des/der + noun-s)', 'wegen + genitive'],
          vocab: [
            { german: 'wegen des Wetters', english: 'because of the weather', notes: 'wegen triggers genitive in formal register (often dative in casual speech).' },
            { german: 'die Meinung der Bevölkerung', english: 'the opinion of the population' },
            { german: 'trotz', english: 'despite', notes: '+ genitive' },
            { german: 'innerhalb / außerhalb', english: 'within / outside', notes: '+ genitive' },
            { german: 'das Eigentum', english: 'the property' },
            { german: 'die Ansicht der Experten', english: "the experts' opinion" },
            { german: 'der Einfluss der Medien', english: 'the influence of the media' },
            { german: 'die Stellungnahme der Regierung', english: "the government's statement" },
            { german: 'wegen des Mangels an', english: 'due to the lack of', notes: 'used to express a reason' },
            { german: 'die Reaktion der Öffentlichkeit', english: "the public's reaction" },
            { german: 'der Zweck der Kampagne', english: 'the purpose of the campaign' },
            { german: 'die Haltung der Jugend', english: 'the attitude of the young people' },
            { german: 'aufgrund des Drucks', english: 'due to the pressure', notes: 'alternative to wegen' },
            { german: 'die Folgen der Entscheidung', english: 'the consequences of the decision' },
            { german: 'die Meinung der Fachleute', english: 'the opinion of the specialists' },
          ],
        },
      ],
    },
    {
      key: 'professional-german',
      title: 'Professional German',
      position: 10,
      notes: 'B2.1 -- passive voice, formal writing, professional situations.',
      units: [
        {
          title: 'Passive Voice',
          source: 'CEFR',
          objectives: ['form and use the passive voice in present and past'],
          grammar_focus: ['werden-passive (present & Perfekt)', 'passive with modal verbs'],
          vocab: [
            { german: 'wird gemacht', english: 'is being done/made' },
            { german: 'wurde gebaut', english: 'was built' },
            { german: 'von / durch', english: 'by', notes: 'Marks the agent in passive constructions.' },
            { german: 'man', english: 'one, people', notes: 'Informal alternative to passive in spoken German -- Germans often prefer "man macht das so" over passive in casual speech.' },
            { german: 'das Passiv', english: 'the passive voice' },
            { german: 'Das Projekt wird gerade bearbeitet', english: 'The project is currently being processed' },
            { german: 'Die Straße wird morgen gesperrt', english: 'The street will be closed tomorrow' },
            { german: 'Das Problem muss gelöst werden', english: 'The problem needs to be solved', notes: 'passive with modal verb müssen' },
            { german: 'Die Entscheidung wird heute getroffen', english: 'The decision will be made today' },
            { german: 'Die Ware wird von unserem Team geprüft', english: 'The goods are being checked by our team', notes: 'emphasizing the doer with von' },
            { german: 'Die Firma wird verkauft', english: 'The company is being sold' },
            { german: 'Das Auto wird gerade gewaschen', english: 'The car is being washed' },
            { german: 'Die Daten werden aktualisiert', english: 'The data is being updated' },
            { german: 'Die Änderungen werden überprüft', english: 'The changes are being reviewed' },
            { german: 'Das Meeting wird von unserem Chef geleitet', english: 'The meeting is being led by our boss', notes: 'emphasizing the doer with von' },
          ],
        },
        {
          title: 'Nominalization & Formal Writing',
          source: 'CEFR',
          objectives: ['convert verbs and adjectives into nouns for formal writing'],
          grammar_focus: ['nominalization patterns (-ung, -heit, -keit)', 'formal connectors (zudem, dennoch)'],
          vocab: [
            { german: 'die Entscheidung', english: 'the decision', notes: 'from entscheiden' },
            { german: 'die Möglichkeit', english: 'the possibility' },
            { german: 'zudem', english: 'moreover' },
            { german: 'dennoch', english: 'nevertheless' },
            { german: 'im Hinblick auf', english: 'with regard to', notes: 'Formal connector.' },
            { german: 'die Realisierung', english: 'the realization' },
            { german: 'die Umsetzung', english: 'the implementation' },
            { german: 'die Entwicklung', english: 'the development' },
            { german: 'die Verantwortung', english: 'the responsibility' },
            { german: 'die Flexibilität', english: 'the flexibility' },
            { german: 'die Kreativität', english: 'the creativity' },
            { german: 'die Priorität', english: 'the priority' },
            { german: 'sich konzentrieren auf', english: 'to focus on', notes: 'common phrase in formal and informal contexts' },
            { german: 'in Bezug auf', english: 'with regard to', notes: "alternative to 'im Hinblick auf'" },
            { german: 'trotzdem', english: 'nevertheless', notes: "informal alternative to 'dennoch'" },
            { german: 'die Erfahrung', english: 'the experience' },
            { german: 'die Fähigkeit', english: 'the ability' },
          ],
        },
        {
          title: 'Job Interviews & Negotiation',
          source: 'CEFR',
          objectives: ['handle a job interview', 'negotiate professionally'],
          grammar_focus: ['Konjunktiv II for polite requests (Ich würde gern…)', 'formal professional vocabulary'],
          vocab: [
            { german: 'Ich würde gern…', english: 'I would like to…', notes: 'Polite/professional register.' },
            { german: 'die Stärken und Schwächen', english: 'strengths and weaknesses' },
            { german: 'das Gehalt verhandeln', english: 'to negotiate salary' },
            { german: 'die Bewerbung', english: 'the application' },
            { german: 'Ich bringe … Erfahrung mit', english: 'I bring … experience' },
            { german: 'der Arbeitsplatz', english: 'workplace' },
            { german: 'die Karrierechancen', english: 'career opportunities' },
            { german: 'das Anforderungsprofil', english: 'job requirements profile' },
            { german: 'sich vorstellen', english: 'to introduce oneself' },
            { german: 'die Teamarbeit', english: 'teamwork' },
            { german: 'die Kommunikationsfähigkeit', english: 'communication skills' },
            { german: 'eine Herausforderung sein', english: 'to be a challenge' },
            { german: 'eine langfristige Perspektive', english: 'long-term perspective' },
            { german: 'die Flexibilität', english: 'flexibility' },
            { german: 'zeitweise Überstunden machen', english: 'to work overtime occasionally' },
            { german: 'die Weiterbildungsmöglichkeiten', english: 'opportunities for further training' },
            { german: 'sich bewerben', english: 'to apply' },
          ],
        },
      ],
    },
    {
      key: 'nuance-debate',
      title: 'Nuance & Debate',
      position: 11,
      notes: 'B2.2 -> B2.3 -- hypotheticals, reported speech, persuasion.',
      units: [
        {
          title: 'Konjunktiv II — Hypotheticals',
          source: 'CEFR',
          objectives: ['express hypothetical situations and wishes'],
          grammar_focus: ['würde + infinitive', 'irregular Konjunktiv II forms (wäre, hätte, könnte)'],
          vocab: [
            { german: 'Wenn ich Zeit hätte…', english: 'if I had time…' },
            { german: 'Ich wäre gern…', english: 'I would like to be…' },
            { german: 'An deiner Stelle würde ich…', english: 'in your place, I would…', notes: 'Very natural way to give advice.' },
            { german: "Das wär's", english: "that would be it, that's it", notes: 'Casual closing phrase.' },
            { german: 'als ob', english: 'as if', notes: '+ Konjunktiv II' },
            { german: 'würde ich Ihnen empfehlen', english: 'I would recommend to you' },
            { german: 'es wäre besser, wenn', english: 'it would be better if' },
            { german: 'könnte man dann', english: 'one could then', notes: 'used to suggest a hypothetical follow-up action' },
            { german: 'hätte ich gewusst', english: 'had I known', notes: 'used to express regret or surprise about a past situation' },
            { german: 'würde das bedeuten', english: 'that would mean', notes: 'used to discuss hypothetical consequences' },
            { german: 'die Konsequenz wäre', english: 'the consequence would be', notes: 'used to discuss potential outcomes' },
            { german: 'ich würde vorschlagen', english: 'I would suggest', notes: 'used in formal or professional settings' },
            { german: 'es wäre sinnvoll, wenn', english: 'it would make sense if', notes: 'used to propose a hypothetical solution' },
            { german: 'wenn man könnte', english: 'if one could', notes: 'used to express a hypothetical wish or possibility' },
          ],
        },
        {
          title: 'Reported Speech',
          source: 'CEFR',
          objectives: ['report what others said', 'recognize Konjunktiv I in news and formal contexts'],
          grammar_focus: ['Konjunktiv I forms (er sei, er habe)', 'indirect speech word order'],
          vocab: [
            { german: 'Er sagte, er sei…', english: 'he said he was…', notes: 'Konjunktiv I, common in journalism.' },
            { german: 'Sie behauptet, dass…', english: 'she claims that…' },
            { german: 'angeblich', english: 'allegedly, supposedly' },
            { german: 'laut Aussage von…', english: 'according to the statement of…' },
            { german: 'er meinte', english: 'he said, remarked', notes: 'A more casual reporting verb than "sagte".' },
            { german: 'die Aussage', english: 'the statement' },
            { german: 'er gibt an', english: 'he claims' },
            { german: 'die Behauptung', english: 'the claim' },
            { german: 'laut Bericht', english: 'according to the report' },
            { german: 'es heißt', english: 'it is said', notes: 'often used in informal conversations' },
            { german: 'er soll', english: 'he supposedly', notes: 'used to express doubt or uncertainty' },
            { german: 'die Meinung', english: 'the opinion' },
            { german: 'er äußert sich', english: 'he expresses himself', notes: 'often used in formal or news contexts' },
            { german: 'die Stellungnahme', english: 'the statement', notes: 'often used in formal or official contexts' },
            { german: 'es wird behauptet', english: 'it is claimed', notes: 'used in formal or written language' },
          ],
        },
        {
          title: 'Debating & Persuading',
          source: 'CEFR',
          objectives: ['build arguments', 'concede points', 'persuade in discussion'],
          grammar_focus: ['concessive connectors (obwohl, trotzdem)', 'structuring an argument'],
          vocab: [
            { german: 'obwohl', english: 'although' },
            { german: 'trotzdem', english: 'nevertheless, still' },
            { german: 'einerseits … andererseits', english: 'on one hand … on the other hand' },
            { german: 'Das Argument überzeugt mich (nicht)', english: "the argument does(n't) convince me" },
            { german: 'Ich gebe zu, dass…', english: 'I admit that…' },
            { german: 'ein Gegenargument', english: 'a counterargument' },
            { german: 'dafür sprechen', english: 'to speak in favor of something', notes: 'used to present an argument' },
            { german: 'dagegen sprechen', english: 'to speak against something', notes: 'used to present a counterargument' },
            { german: 'ein Argument vorbringen', english: 'to put forward an argument' },
            { german: 'ich teile deine Meinung', english: 'I share your opinion', notes: 'used to show agreement' },
            { german: 'ich bin anderer Meinung', english: 'I have a different opinion', notes: 'used to politely disagree' },
            { german: 'das ist ein wichtiger Punkt', english: "that's an important point", notes: 'used to acknowledge a valid argument' },
            { german: 'das ist nicht ganz richtig', english: "that's not entirely correct", notes: 'used to politely correct someone' },
            { german: 'ich verstehe, was du meinst', english: 'I understand what you mean', notes: 'used to show understanding before responding' },
            { german: 'das ist ein guter Einwand', english: "that's a good objection", notes: 'used to acknowledge a valid counterargument' },
          ],
        },
      ],
    },
    {
      key: 'advanced-fluency',
      title: 'Advanced Fluency',
      position: 12,
      notes: 'C1 -- idiom, literary/academic register, near-native style.',
      units: [
        {
          title: 'Idioms & Colloquial Register',
          source: 'CEFR',
          objectives: ['recognize and use common idioms', 'shift naturally between formal and informal register'],
          grammar_focus: ['idiomatic expressions', 'particle usage (doch, mal, halt) for natural tone'],
          vocab: [
            { german: 'die Daumen drücken', english: "to keep one's fingers crossed", notes: 'Literally "press thumbs".' },
            { german: 'ins Blaue hinein', english: 'on a whim, without a plan' },
            { german: 'das ist mir Wurst', english: "I don't care", notes: 'Literally "that\'s sausage to me" -- very colloquial, friends only.' },
            { german: 'na klar', english: 'sure, of course', notes: 'Casual.' },
            { german: 'doch', english: 'yet, still, contradiction particle', notes: 'Used to contradict a negative statement, e.g. "Du kommst nicht?" "Doch!"' },
            { german: 'auf dem richtigen Dampfer sein', english: 'to be on the right track' },
            { german: 'mal sehen', english: "we'll see", notes: 'often used to express uncertainty or hesitation' },
            { german: 'jemandem einen Gefallen tun', english: 'to do someone a favor' },
            { german: 'das ist nicht mein Bier', english: "that's not my problem", notes: "used to express that something is not one's responsibility" },
            { german: 'etwas auf die lange Bank schieben', english: 'to put something off until later', notes: 'used to describe procrastination' },
            { german: 'jemandem Halt sagen', english: 'to tell someone to stop', notes: 'used to express that someone should stop doing something' },
            { german: 'mal langsam', english: 'slow down', notes: 'used to ask someone to slow down or be more patient' },
            { german: 'das kommt nicht in Frage', english: "that's out of the question", notes: 'used to express strong disagreement or refusal' },
            { german: 'jemandem den Rücken freihalten', english: "to cover someone's back", notes: 'used to describe supporting or helping someone' },
            { german: 'etwas ausbaden', english: 'to suffer the consequences', notes: 'used to describe having to deal with the negative results of an action' },
          ],
        },
        {
          title: 'Literary & Academic Texts',
          source: 'CEFR',
          objectives: ['read and discuss literary or academic excerpts', 'recognize complex sentence structures'],
          grammar_focus: ['extended attributes (erweiterte Partizipialattribute)', 'complex subordinate clause chains'],
          vocab: [
            { german: 'die Erzählperspektive', english: 'the narrative perspective' },
            { german: 'die These', english: 'the thesis' },
            { german: 'im Gegensatz zu', english: 'in contrast to' },
            { german: 'Es lässt sich sagen, dass…', english: 'it can be said that…' },
            { german: 'die Anspielung', english: 'the allusion' },
            { german: 'die Interpretation', english: 'the interpretation' },
            { german: 'sich auf etwas beziehen', english: 'to refer to something', notes: 'common in academic and literary discussions' },
            { german: 'die Analyse', english: 'the analysis' },
            { german: 'ein Beispiel dafür ist', english: 'an example of this is', notes: 'useful for illustrating points' },
            { german: 'die Kritik', english: 'the criticism', notes: 'can refer to literary criticism or critique of an idea' },
            { german: 'sich mit etwas auseinandersetzen', english: 'to grapple with something', notes: 'common in discussions of complex topics' },
            { german: 'die Diskussion', english: 'the discussion' },
            { german: 'ein Aspekt davon ist', english: 'one aspect of it is', notes: 'helpful for breaking down complex topics' },
            { german: 'die Schlussfolgerung', english: 'the conclusion', notes: 'important in academic and literary texts' },
            { german: 'sich äußern über', english: 'to express an opinion about', notes: 'useful in discussions and debates' },
            { german: 'die Betonung', english: 'the emphasis', notes: 'can refer to emphasis in speech or writing' },
            { german: 'in diesem Zusammenhang', english: 'in this context', notes: 'helpful for clarifying discussions' },
          ],
        },
        {
          title: 'Advanced Connectors & Style',
          source: 'CEFR',
          objectives: ['write and speak with stylistic variety at near-native fluency'],
          grammar_focus: ['advanced connectors (zumal, indes, mithin)', 'stylistic register shifting'],
          vocab: [
            { german: 'zumal', english: 'especially since' },
            { german: 'indes', english: 'however, meanwhile', notes: 'Literary register.' },
            { german: 'mithin', english: 'therefore, consequently', notes: 'Formal/literary.' },
            { german: 'geschweige denn', english: 'let alone' },
            { german: 'alles in allem', english: 'all in all', notes: 'Good natural wrap-up phrase for conversation or essays.' },
            { german: 'nämlich', english: 'namely', notes: 'used to add a clarifying explanation' },
            { german: 'deshalb', english: 'therefore', notes: 'commonly used in spoken and written German' },
            { german: 'darüber hinaus', english: 'furthermore', notes: 'used to add additional information' },
            { german: 'hingegen', english: 'on the other hand', notes: 'used for contrasting ideas' },
            { german: 'in diesem Zusammenhang', english: 'in this context', notes: 'used to specify a particular situation' },
            { german: 'mithilfe von', english: 'by means of', notes: 'used to describe how something is done' },
            { german: 'im Großen und Ganzen', english: 'all in all', notes: "already covered, but 'im Großen und Ganzen' is more conversational" },
            { german: 'jedenfalls', english: 'in any case', notes: 'used to conclude or summarize a point' },
            { german: 'eben', english: 'just', notes: 'used to emphasize a point or add a reason' },
            { german: 'somit', english: 'thus', notes: 'used to conclude or summarize a point' },
            { german: 'demzufolge', english: 'consequently', notes: 'used to describe a result or consequence' },
          ],
        },
      ],
    },
  ],
};
