// js/exercises/conjugationMatch.js — "Verb Conjugation Match": a matching-
// grid exercise pairing pronouns (ich/du/er.../wir/ihr/sie) with the correct
// conjugated form of a verb, one verb per round. Reuses the same tap-to-
// match UI pattern as the vocab-matching phase in pages/runner.js, but
// pronoun labels aren't unique per verb the way German/English word pairs
// are, so unlike that phase this can't put several verbs into one shared
// grid — it does one verb per round instead, cycling through a few verbs
// per session.
//
// Scope for v1: only verbs the learner has already been introduced to (has
// a progress row for — see pickIntroducedVerbs below), and conjugations are
// generated by the LLM per session rather than a hand-authored table (see
// prompts.js buildConjugationPrompt for why). Next step, per Luke: expand to
// verbs ahead of where the learner currently is in the curriculum.
import * as store from '../store.js';
import { buildConjugationPrompt } from '../prompts.js';
import { quizCall } from '../ai.js';
import { escapeHtml as esc } from '../chatui.js';
import { mountFeedbackFlag } from '../feedback.js';

const PRONOUNS = [
  { key: 'ich', label: 'ich' },
  { key: 'du', label: 'du' },
  { key: 'er_sie_es', label: 'er / sie / es' },
  { key: 'wir', label: 'wir' },
  { key: 'ihr', label: 'ihr' },
  { key: 'sie_Sie', label: 'sie / Sie' },
];

const CANDIDATE_POOL = 10;  // verbs sent to the LLM for conjugation
const ROUND_SIZE = 4;       // rounds actually played per session

export const meta = {
  id: 'conjugation-match',
  title: 'Verb Conjugation Match',
  blurb: "Match ich/du/er... to the right conjugated form — one verb at a time, drawn from verbs you've already practiced.",
};

export async function mount(el, ctx) {
  renderStatus(el, 'Finding verbs you\'ve already practiced…');
  const candidates = await pickIntroducedVerbs(ctx.userId);

  if (!candidates.length) {
    renderEmpty(el, ctx, "No verbs yet", "Once you've practiced a few verb phrases in your lessons, they'll show up here to conjugate. Keep going with Today's lesson!");
    return;
  }

  renderStatus(el, 'Building conjugations…');
  // Same "never let feedback plumbing break the exercise" defensiveness as
  // runner.js: if content_feedback isn't queryable yet (e.g. Supabase
  // schema not re-run), just generate without past-issues context.
  const pastIssues = await store.allContentFeedback(ctx.userId)
    .then((all) => store.recentFeedbackNotes(all, 'conjugation_match'))
    .catch(() => []);
  let table;
  try {
    table = await quizCall(buildConjugationPrompt(shuffle(candidates).slice(0, CANDIDATE_POOL), pastIssues), 'Generate the conjugation table now.');
  } catch (e) {
    renderError(el, ctx, e.message);
    return;
  }

  const byId = Object.fromEntries(candidates.map((v) => [v.vocab_id, v]));
  // Dedupe by normalized infinitive before slicing to ROUND_SIZE — nothing
  // upstream guarantees the LLM's returned verb list is unique (candidates
  // sent to it can include near-duplicate phrases, e.g. two different "Ich
  // ..." vocab rows that both conjugate the same underlying verb), and a
  // repeated verb would show the identical round twice in one session.
  const seenVerbs = new Set();
  const rounds = (table.verbs || [])
    .filter((r) => r.id && byId[r.id] && r.forms && PRONOUNS.every((p) => (r.forms[p.key] || '').trim()))
    .filter((r) => {
      const key = (r.infinitive || byId[r.id].german || '').trim().toLowerCase();
      if (!key || seenVerbs.has(key)) return false;
      seenVerbs.add(key);
      return true;
    })
    .slice(0, ROUND_SIZE);

  if (!rounds.length) {
    renderError(el, ctx, "Couldn't build a conjugation round from those verbs this time.");
    return;
  }

  let idx = 0;
  renderRound();

  function renderRound() {
    if (idx >= rounds.length) {
      el.innerHTML = `
        <div class="page-head"><div class="eyebrow">Exercise complete</div><h1>${esc(meta.title)}</h1></div>
        <div class="card">
          <h3 style="margin-top:0">Nice — ${rounds.length} verb${rounds.length > 1 ? 's' : ''} conjugated.</h3>
          <div class="row wrap" style="gap:8px;margin-top:12px">
            <button class="btn primary" id="ex-again">Practice more verbs</button>
            <button class="btn ghost" id="ex-back">← Back to exercises</button>
          </div>
        </div>
      `;
      el.querySelector('#ex-again').onclick = () => mount(el, ctx);
      el.querySelector('#ex-back').onclick = () => ctx.go('exercises');
      return;
    }

    const r = rounds[idx];
    const src = byId[r.id];
    // Matched by TEXT, not by which pronoun the LLM originally generated a
    // given form for: several pronouns legitimately share an identical
    // conjugated form in German (wir/sie/Sie always do — "wir möchten" and
    // "Sie möchten" are both correct spelled "möchten" — and it's not rare,
    // it's the normal pattern for every verb). Tagging tiles by pronoun id
    // and requiring an exact id match would mark a factually-correct pairing
    // wrong just because the learner happened to tap the "other" identical
    // tile. Comparing normalized text instead means any tile with the right
    // spelling counts, however many pronouns share it.
    const norm = (s) => (s || '').trim().toLowerCase();
    const left = PRONOUNS.map((p) => ({ text: p.label, answer: r.forms[p.key].trim() }));
    const right = shuffle(PRONOUNS.map((p) => ({ text: r.forms[p.key].trim() })));

    el.innerHTML = `
      <div class="row spread" style="margin-bottom:14px">
        <div>
          <div class="eyebrow">Exercise · Verb ${idx + 1} of ${rounds.length}</div>
          <h1 style="font-size:1.4rem">${esc(r.infinitive || src.german)}</h1>
          <div class="unit-meta" style="margin-top:2px">from "${esc(src.german)}" — ${esc(src.english)}</div>
        </div>
        <button class="btn ghost sm" id="ex-back">← Exercises</button>
      </div>
      <div class="card">
        <h3 style="margin:0 0 4px">Tap a pronoun, then its matching conjugated form</h3>
        <p class="muted" style="font-size:.82rem;margin-top:0">Some pronouns share the same form (e.g. wir/sie/Sie) — either matching tile counts.</p>
        <div class="match-grid">
          <div class="match-col">${left.map((x) => `<button class="match-item" data-side="pn" data-answer="${esc(x.answer)}">${esc(x.text)}</button>`).join('')}</div>
          <div class="match-col">${right.map((x) => `<button class="match-item" data-side="vb" data-form="${esc(x.text)}">${esc(x.text)}</button>`).join('')}</div>
        </div>
        <div class="row spread" style="margin-top:14px">
          <span class="muted" id="round-progress">0 / ${left.length} matched</span>
          <button class="btn primary" id="round-continue" disabled>${idx + 1 < rounds.length ? 'Next verb →' : 'Finish →'}</button>
        </div>
        <div class="fb-slot" style="margin-top:10px"></div>
      </div>
    `;
    el.querySelector('#ex-back').onclick = () => ctx.go('exercises');
    mountFeedbackFlag(el.querySelector('.fb-slot'), ctx.userId, {
      contextType: 'conjugation_match',
      itemType: null,
      unitId: null,
      unitTitle: null,
      prompt: r.infinitive || src.german,
      answer: PRONOUNS.map((p) => `${p.key}=${r.forms[p.key]}`).join(', '),
    });

    let selected = null;
    let matched = 0;
    el.querySelectorAll('.match-item').forEach((b) => b.onclick = () => {
      if (b.classList.contains('matched')) return;
      if (b.dataset.side === 'pn') {
        el.querySelectorAll('.match-item[data-side="pn"]').forEach((x) => x.classList.remove('sel'));
        b.classList.add('sel');
        selected = { el: b, answer: norm(b.dataset.answer) };
        return;
      }
      if (!selected) return;
      if (norm(b.dataset.form) === selected.answer) {
        b.classList.add('matched'); selected.el.classList.add('matched'); selected.el.classList.remove('sel');
        selected = null; matched++;
        el.querySelector('#round-progress').textContent = `${matched} / ${left.length} matched`;
        if (matched === left.length) el.querySelector('#round-continue').disabled = false;
      } else {
        b.classList.add('miss'); const bad = selected.el;
        setTimeout(() => { b.classList.remove('miss'); bad.classList.remove('sel'); }, 450);
        selected = null;
      }
    });
    el.querySelector('#round-continue').onclick = () => { idx++; renderRound(); };
  }
}

// Candidate verb vocab: a first-person example phrase ("Ich brauche — I
// need") OR any entry whose English gloss is an infinitive ("to ..."),
// regardless of how many German words it takes to say it — a bare
// dictionary infinitive ("brauchen — to need", rare in this curriculum) or,
// just as often, a multi-word infinitive phrase (reflexive "sich duschen —
// to shower", separable/particle "spazieren gehen — to go for a walk",
// "Rad fahren — to ride a bike", noun-object "ein Ticket kaufen — to buy a
// ticket"). Previously this only matched single-word bare infinitives or
// "ich ..." phrases, silently excluding every multi-word "to ..." entry —
// about 48 of 645 seed vocab rows, mostly common reflexive/separable verbs —
// even though the LLM call below is already written to handle exactly this
// (it explicitly strips trailing complements like "gern"/"aus"). This is a
// loose, cheap client-side pre-filter; the LLM call in mount() does the real
// work of confirming it's actually a single conjugatable verb and skips it
// otherwise, so a false positive here just gets dropped, not shown wrong.
// "Introduced" = has a progress row with times_seen > 0, the same "seen"
// convention pages/runner.js uses (see mountRecognitionStep there).
async function pickIntroducedVerbs(userId) {
  const [sections, progress] = await Promise.all([store.getCurriculum(userId), store.allProgress(userId)]);
  const progByItem = {};
  progress.forEach((p) => { progByItem[p.item_id] = p; });

  const candidates = [];
  sections.forEach((s) => s.units.forEach((u) => (u.vocab || []).forEach((v) => {
    if (!v.german || !v.english) return;
    const g = v.german.trim();
    const isInfinitivePhrase = /^to\s+/i.test(v.english.trim());
    const isFirstPersonPhrase = /^ich\s+\S+/i.test(g);
    if (!isInfinitivePhrase && !isFirstPersonPhrase) return;
    if ((progByItem[v.vocab_id]?.times_seen || 0) <= 0) return;
    candidates.push(v);
  })));
  return candidates;
}

function renderStatus(el, msg) {
  el.innerHTML = `<div class="page-head"><div class="eyebrow">Exercise</div><h1>${esc(meta.title)}</h1><p>${esc(msg)}</p></div>`;
}

function renderEmpty(el, ctx, title, body) {
  el.innerHTML = `
    <div class="page-head"><div class="eyebrow">Exercise</div><h1>${esc(meta.title)}</h1></div>
    <div class="empty">
      <h3>${esc(title)}</h3>
      <p>${esc(body)}</p>
      <button class="btn" id="ex-back" style="margin-top:8px">← Back to exercises</button>
    </div>
  `;
  el.querySelector('#ex-back').onclick = () => ctx.go('exercises');
}

function renderError(el, ctx, message) {
  // A missing/invalid API key surfaces here as a normal call failure, but
  // "Try again" just fails the same way a second time — point straight at
  // the fix instead (mirrors the same handling in pages/runner.js).
  const isKeyError = /add it in settings/i.test(message || '');
  el.innerHTML = `
    <div class="page-head"><div class="eyebrow">Exercise</div><h1>${esc(meta.title)}</h1></div>
    <div class="card">
      <p class="verdict wrong">${esc(message)}</p>
      <div class="row" style="margin-top:8px;gap:8px">
        ${isKeyError
          ? '<button class="btn primary" id="ex-settings">Go to Settings</button>'
          : '<button class="btn primary" id="ex-retry">Try again</button>'}
        <button class="btn ghost" id="ex-back">← Back to exercises</button>
      </div>
    </div>
  `;
  if (isKeyError) el.querySelector('#ex-settings').onclick = () => ctx.go('settings');
  else el.querySelector('#ex-retry').onclick = () => mount(el, ctx);
  el.querySelector('#ex-back').onclick = () => ctx.go('exercises');
}

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}
